### ISSUE TITLE
Is there any difference in implementation of cross conv and inception conv?

### ISSUE THREAD

**Issue by ydhongHIT** [yuqing-liu-dut/Cross-SRN#1]
How do you make the cross convolution explictly extract the edge information? I didn't find the related codes.

**Comment by yuqing-liu-dut** [comment]
The inception conv builds the asymmetric filters sequentially, while cross conv makes them parallel. In fact we mainly discuss the difference between inception (Seq) and the cross-conv (Cross) in the paper.

**Comment by ydhongHIT** [comment]
> The inception conv builds the asymmetric filters sequentially, while cross conv makes them parallel. In fact we mainly discuss the difference between inception (Seq) and the cross-conv (Cross) in the paper.

Thanks for your reply. So the only difference is the sequential or parallel? In your paper, I find some discussions as follows.
![1642747482](https://user-images.githubusercontent.com/42939497/150479607-fc98c9cc-427d-463e-af88-506e3fefadc9.png)
You say the Inception filters can not explicitly extract edge features but I can not understand why cross filters make it. In fact, [the cvpr2017 paper](https://openaccess.thecvf.com/content_cvpr_2017/papers/Peng_Large_Kernel_Matters_CVPR_2017_paper.pdf) has proposed the sequentially asymmetric filters.
